spring:
  datasource:
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(ZPWAIrYvVGRbFYg0jksaFyLkQOzwvHs9mY5M2VJbK1QbTuQMOZTHVpJK86X94XNROPjeNTKprd01lKTTQO9pjfmSnCYZHWRfhaMa/3ftgazs5hC4OnHs0Q==)
    username: ENC(MrJMwUIMZJUxxMzE0JVP/A==)
    password: ENC(Kq6sm0YPnkGjzw4m23SgYA/hQ7bcnI8R)

github:
  client-id : ENC(icW2dKR7lQ0jro3v+dWGf1ehhG4Be7bDtU9BeIy6H38=)
  client-secret : ENC(kYTfbJksLKEDJR1z3LKtfjrqG6G/u0nu4xfx6KJZCHUyQIjCYCnTls70Uyc2w7sNfYdY/17n47o=)
---
spring:
  profiles: local

logging:
  level:
    com:
      naru:
        howaboutthis: info
